#!/usr/bin/env bash
# calibrate-touch.sh — Interactive resistive touch calibration for the LCD HAT.
#
# Writes calibration values to ~/.squelch-touch-cal, which start-lcd.sh
# sources automatically on each launch.
#
# Usage: ./calibrate-touch.sh
#
# The script asks you to tap four corners of the screen in order.
# It reads raw ADS7846 events from /dev/input/event0 (override with
# SQUELCH_TOUCH_DEV) and computes the XMIN/XMAX/YMIN/YMAX ranges.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
VENV_PYTHON="$SCRIPT_DIR/pygame-display/.venv-pygame-display/bin/python3"
DEV="${SQUELCH_TOUCH_DEV:-/dev/input/event0}"
CAL_FILE="$HOME/.squelch-touch-cal"

if [[ ! -e "$DEV" ]]; then
    echo "Error: touch device $DEV not found." >&2
    exit 1
fi

if [[ ! -x "$VENV_PYTHON" ]]; then
    echo "Error: Python venv not found. Run setup-pi.sh first." >&2
    exit 1
fi

echo ""
echo "━━━ Touch Screen Calibration ━━━"
echo ""
echo "  Tap each corner of the screen when prompted."
echo "  Hold your finger briefly and release — the tap is recorded on release."
echo ""

"$VENV_PYTHON" - "$DEV" "$CAL_FILE" <<'PYEOF'
import sys, struct, os

dev      = sys.argv[1]
cal_file = sys.argv[2]

EV_FMT     = 'qqHHi'
EV_SIZE    = struct.calcsize(EV_FMT)
EV_ABS, EV_KEY, EV_SYN = 3, 1, 0
ABS_X, ABS_Y, BTN_TOUCH = 0, 1, 330

CORNERS = [
    ("TOP-LEFT",     "top-left"),
    ("TOP-RIGHT",    "top-right"),
    ("BOTTOM-LEFT",  "bottom-left"),
    ("BOTTOM-RIGHT", "bottom-right"),
]

samples = []

with open(dev, 'rb') as f:
    for label, hint in CORNERS:
        print(f"  Tap the {label} corner ({hint} of the screen)...", flush=True)
        rx = ry = 0
        while True:
            data = f.read(EV_SIZE)
            _, _, typ, code, val = struct.unpack(EV_FMT, data)
            if typ == EV_ABS:
                if code == ABS_X: rx = val
                elif code == ABS_Y: ry = val
            elif typ == EV_KEY and code == BTN_TOUCH and val == 0:
                print(f"    raw: x={rx} y={ry}", flush=True)
                samples.append((rx, ry))
                break

tl, tr, bl, br = samples

# Derive axis ranges from the four corners.
# X increases left→right (confirmed from corner test data).
# Y increases bottom→top (high raw Y = top of screen, so invert).
x_vals = [tl[0], tr[0], bl[0], br[0]]
y_vals = [tl[1], tr[1], bl[1], br[1]]

xmin = min(x_vals)
xmax = max(x_vals)
ymin = min(y_vals)
ymax = max(y_vals)

# Add a small margin inward so edge taps aren't clipped
margin_x = int((xmax - xmin) * 0.03)
margin_y = int((ymax - ymin) * 0.03)
xmin = max(0,    xmin - margin_x)
xmax = min(4095, xmax + margin_x)
ymin = max(0,    ymin - margin_y)
ymax = min(4095, ymax + margin_y)

cal = f"""# squelch-tail touch calibration — generated by calibrate-touch.sh
export SQUELCH_TOUCH_XMIN={xmin}
export SQUELCH_TOUCH_XMAX={xmax}
export SQUELCH_TOUCH_YMIN={ymin}
export SQUELCH_TOUCH_YMAX={ymax}
export SQUELCH_TOUCH_SWAP_XY=0
export SQUELCH_TOUCH_INVERT_X=0
export SQUELCH_TOUCH_INVERT_Y=1
"""

with open(cal_file, 'w') as f:
    f.write(cal)

print()
print(f"  Calibration saved to {cal_file}")
print(f"  XMIN={xmin}  XMAX={xmax}  YMIN={ymin}  YMAX={ymax}")
print()
print("  Re-run ./calibrate-touch.sh any time to recalibrate.")
PYEOF
